#!/system/bin/sh

busybox=/system/xbin/busybox;

if [ ! -e /system/lib/hw/power.tuna.so.bak ]; then
	$busybox mount -o remount,rw /system;
	$busybox cp /system/lib/hw/power.tuna.so /system/lib/hw/power.tuna.so.bak;
	$busybox cp /sbin/power.tuna.so /system/lib/hw/;
	$busybox chmod 644 /system/lib/hw/power.tuna.so;
	$busybox mount -o remount,ro /system;
fi;

if [ ! -e /system/etc/init.d ]; then
	$busybox mount -o remount,rw /system;
	$busybox mkdir /system/etc/init.d;
	$busybox chown -R root.root /system/etc/init.d;
	$busybox chmod -R 755 /system/etc/init.d;
	$busybox mount -o remount,ro /system;
fi;

if [ ! -e /data/fuss ]; then
	$busybox mkdir /data/fuss;
	$busybox chown -R root.root /data/fuss;
	$busybox chmod -R 755 /data/fuss;
	$busybox cp /sbin/fuss /data/fuss/;
	$busybox cp /sbin/reflash /data/fuss/;
	$busybox chmod 755 /data/fuss/fuss;
	$busybox chmod 755 /data/fuss/reflash;
fi;

if [ ! -e /system/bin/fuss ]; then
	$busybox mount -o remount,rw /system;
	$busybox ln -s /data/fuss/fuss /system/bin/fuss;
	$busybox ln -s /data/fuss/reflash /system/bin/reflash;
	$busybox mount -o remount,ro /system;
fi;
