#!/system/bin/sh

busybox=/sbin/busybox
fstrim=/sbin/fstrim
zipalign=/sbin/zipalign

# powerHAL fix
if [ ! -e /system/lib/hw/power.tuna.so.bak ] ; then
  $busybox mount -o remount,rw /system
  $busybox mv /system/lib/hw/power.tuna.so /system/lib/hw/power.tuna.so.bak
  $busybox cp /sbin/power.tuna.so /system/lib/hw/
  $busybox chmod 644 /system/lib/hw/power.tuna.so
  $busybox mount -o remount,ro /system
fi

# FUSS
if [ ! -e /data/fuss ] ; then
  $busybox mkdir /data/fuss
  $busybox chown -R root.root /data/fuss
  $busybox chmod -R 755 /data/fuss
  $busybox cp /sbin/fuss /data/fuss/
  $busybox cp /sbin/reflash /data/fuss/
  $busybox chmod 755 /data/fuss/fuss
  $busybox chmod 755 /data/fuss/reflash
fi

if [ ! -e /system/bin/fuss ] ; then
  $busybox mount -o remount,rw /system
  $busybox ln -s /data/fuss/fuss /system/bin/fuss
  $busybox ln -s /data/fuss/reflash /system/bin/reflash
  $busybox mount -o remount,ro /system
fi

# init.d support
if [ ! -e /system/etc/init.d ] ; then
  $busybox mount -o remount,rw /system
  $busybox mkdir /system/etc/init.d
  $busybox chown -R root.root /system/etc/init.d
  $busybox chmod -R 755 /system/etc/init.d
  $busybox mount -o remount,ro /system
fi

if [ ! -e /system/bin/sysinit ] ; then
  $busybox run-parts /system/etc/init.d
fi

# zipalign apks
LOG_FILE=/data/zipalign.log
ZIPALIGNDB=/data/zipalign.db

if [ -e $LOG_FILE ] ; then
  $busybox rm $LOG_FILE
fi

if [ ! -f $ZIPALIGNDB ] ; then
  $busybox touch $ZIPALIGNDB
fi

$busybox echo "Starting FV Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | $busybox tee -a $LOG_FILE

for DIR in /system/app /data/app ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $($busybox grep "$DIR/$APK" $ZIPALIGNDB|$busybox wc -l) -gt 0 ] ; then
      $busybox echo "Already checked: $DIR/$APK" | $busybox tee -a $LOG_FILE
    else
      $zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        $busybox echo "Already aligned: $DIR/$APK" | $busybox tee -a $LOG_FILE
        $busybox grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || $busybox echo $DIR/$APK >> $ZIPALIGNDB
      else
        $busybox echo "Now aligning: $DIR/$APK" | $busybox tee -a $LOG_FILE
        $zipalign -f 4 $APK /cache/$APK
        $busybox mount -o rw,remount /system
        $busybox cp -f -p /cache/$APK $APK
	$busybox chmod 644 $APK
        $busybox rm -f /cache/$APK
        $busybox grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || $busybox echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done

$busybox mount -o ro,remount /system
$busybox touch $ZIPALIGNDB
$busybox echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | $busybox tee -a $LOG_FILE

# trim file system if wipes have been performed
if [[ ! -e /cache/trimmed ]] || [[ ! -e /data/dalvik-cache/trimmed ]] ; then
  $fstrim /cache
  $fstrim /data
  $busybox touch /cache/trimmed
  $busybox touch /data/dalvik-cache/trimmed
fi

# increase systemui process priority
until [ $($busybox pgrep com.android.systemui) ] ; do
  $busybox sleep 1
done

$busybox renice -17 $($busybox pgrep com.android.systemui)

# wifi module
$busybox insmod /sbin/bcmdhd.ko firmware_path=/system/vendor/firmware/fw_bcmdhd.bin nvram_path=/system/etc/wifi/bcmdhd.cal

# low memory killer whitelist for common launchers
list="com.cyanogenmod.trebuchet com.android.launcher org.adw.launcher org.adwfreak.launcher com.anddoes.launcher com.gau.go.launcherex com.mobint.hololauncher com.mobint.hololauncher.hd com.teslacoilsw.launcher org.zeam"

$busybox sleep 30

for class in $list ; do
  if [ $($busybox pgrep $class) ] ; then
    pid=$($busybox pgrep $class)
    $busybox echo -17 > /proc/$pid/oom_adj
    $busybox chmod 100 /proc/$pid/oom_adj
    break
  fi
done

# disable swappiness if zram is not active
swapsize=$($busybox free | $busybox grep -i swap | $busybox awk '{print $2}')

if [ $swapsize -eq 0 ] ; then
  echo 0 > /proc/sys/vm/swappiness
fi
