#!/system/bin/sh

bbox=/sbin/binaries/busybox
t2fs=/sbin/binaries/tune2fs

# set writeback journalling mode
if [ ! -e /data/writebackenabled ] ; then
  $t2fs -o journal_data_writeback /dev/block/platform/omap/omap_hsmmc.0/by-name/userdata
  $bbox touch /data/writebackenabled
  needreboot=1
fi
if [ ! -e /cache/writebackenabled ] ; then
  $t2fs -o journal_data_writeback /dev/block/platform/omap/omap_hsmmc.0/by-name/cache
  $bbox touch /cache/writebackenabled
  needreboot=1
fi
if [ ! -e /system/writebackenabled ] ; then
  $t2fs -o journal_data_writeback /dev/block/platform/omap/omap_hsmmc.0/by-name/system
  $bbox mount -o remount,rw /system
  $bbox touch /system/writebackenabled
  needreboot=1
fi

# powerHAL fix
if [ ! -e /system/lib/hw/power.tuna.so.bak ] ; then
  $bbox mount -o remount,rw /system
  $bbox mv /system/lib/hw/power.tuna.so /system/lib/hw/power.tuna.so.bak
  $bbox cp /sbin/power.tuna.so /system/lib/hw/
  $bbox chmod 644 /system/lib/hw/power.tuna.so
  needreboot=1
fi

if [ $needreboot -eq 1 ] ; then 
  reboot
fi

# init.d support
if [ ! -e /system/etc/init.d ] ; then
  $bbox mount -o remount,rw /system
  $bbox mkdir /system/etc/init.d
  $bbox chown -R root.root /system/etc/init.d
  $bbox chmod -R 755 /system/etc/init.d
  $bbox mount -o remount,ro /system
fi

$bbox run-parts /system/etc/init.d

# change some processes' cgroups and priorities
until [ $($bbox pgrep com.android.systemui) ] ; do
  $bbox sleep 1
done
$bbox sleep 5

$bbox mkdir /dev/cpuctl/kswapd
$bbox chown system system /dev/cpuctl/kswapd/tasks
$bbox chmod 0660 /dev/cpuctl/kswapd/tasks

$bbox echo 91 > /dev/cpuctl/apps/bg_non_interactive/cpu.shares
$bbox echo 400000 > /dev/cpuctl/apps/bg_non_interactive/cpu.rt_runtime_us
$bbox echo 704 > /dev/cpuctl/kswapd/cpu.shares

$bbox renice -5 $($bbox pgrep com.android.systemui)
$bbox renice 5 $($bbox pgrep kswapd)

$bbox echo $($bbox pgrep com.android.systemui) > /dev/cpuctl/tasks
$bbox echo $($bbox pgrep kswapd) > /dev/cpuctl/kswapd/tasks

# set cgroup_timer_slack for bg_non_interactive tasks
$bbox echo 100000000 > /dev/cpuctl/apps/bg_non_interactive/timer_slack.min_slack_ns

# low memory killer whitelist for common launchers
$bbox sleep 20

list="com.cyanogenmod.trebuchet com.android.launcher org.adw.launcher org.adwfreak.launcher com.anddoes.launcher com.gau.go.launcherex com.mobint.hololauncher com.mobint.hololauncher.hd com.teslacoilsw.launcher org.zeam com.chrislacy.actionlauncher.pro com.android.lmt com.tsf.shell com.miui.mihome2 com.qihoo360.launcher com.gtp.nextlauncher net.alamoapps.launcher"

if [ ! -e /data/nowhitelist ] ; then
  for class in $list ; do
    if [ $($bbox pgrep $class) ] ; then
      pid=$($bbox pgrep $class)
      until [ -e /proc/$pid ] ; do
        $bbox sleep 1
      done
      $bbox echo -17 > /proc/$pid/oom_adj
      break
    fi
  done
fi
